name: Check Build
on:
  pull_request:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21
      - run: ./gradlew build --stacktrace --no-daemon
